%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "Rectified"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 936.91902
Camera1.fy: 929.94662
Camera1.cx: 830.96204
Camera1.cy: 675.24404

# distortion parameters
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.k3: 0.0
Camera1.k4: 0.0

Camera2.fx: 933.75701
Camera2.fy: 926.30638
Camera2.cx: 753.17986
Camera2.cy: 637.92351

# Camera resolution
Camera.width: 1600
Camera.height: 1200

# Camera frames per second 
Camera.fps: 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 5.0
Stereo.b: 0.2

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 1.0, 0., 0.0 , 0.0,
           0.0, 1.0, 0.0, 0.0,
           0.0, 0.0, 1.0, 0.0,
           0.0, 0.0, 0.0, 1.0]

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1.0e-02 # 3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1.0e-02 #2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1.0e-02 # rad/s^1.5
IMU.AccWalk: 1.0e-02 # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 15
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
